out: benchmark.o bubblesort.o quicksort.o

benchmark.o:
	mipsel-linux-gnu-gcc-5 benchmark.c -o benchmark -lm

quicksort.o:
	mipsel-linux-gnu-gcc-5 quicksort.c -o quicksort

bubblesort.o:
	mipsel-linux-gnu-gcc-5 bubblesort.c -o bubblesort